"""
Django settings for travelmobileapi project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from django.conf.global_settings import AUTH_USER_MODEL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--mqs*@ubsl1)u_@^a8js12q9q4@c$f%2a&gv$eh5f@c55kzc0#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


import cloudinary
import cloudinary.uploader
import cloudinary.api

# --- CẤU HÌNH CLOUDINARY (Thêm đoạn này vào cuối file) ---
cloudinary.config(
  cloud_name = "dvcbfmzdl",
  api_key = "199126856568642",
  api_secret = "0MWxdhI4j6d12sSQbZmiGWj1OHk"
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
# --- Thư viện bên thứ 3 ---
    'rest_framework',
    'oauth2_provider',  # <--- Yêu cầu bắt buộc của đề bài (OAuth2)
    'corsheaders',      # Để React Native gọi được API
    'ckeditor',
    'ckeditor_uploader',
    'cloudinary',
    'drf_yasg',

    # --- App của bạn ---
    'travel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'travelmobileapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'travelmobileapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
'ENGINE': 'django.db.backends.mysql',
        'NAME': 'traveldb',  # <--- SỬA THÀNH TÊN MỚI Ở ĐÂY
        'USER': 'root',      # Kiểm tra lại user MySQL của bạn
        'PASSWORD': 'root',  # Kiểm tra lại mật khẩu MySQL của bạn
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

AUTH_USER_MODEL = 'travel.User'
AUTH_PASSWORD_VALIDATORS = []

CORS_ORIGIN_ALLOW_ALL = True

import os  # Kiểm tra trên cùng file có dòng này chưa, nếu chưa thì thêm vào

# --- CẤU HÌNH MEDIA (Nơi lưu file ảnh) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- CẤU HÌNH CKEDITOR (Sửa lỗi ImproperlyConfigured) ---
# Thư mục con bên trong media để chứa ảnh của bài viết
CKEDITOR_UPLOAD_PATH = "uploads/"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# settings.py

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # DÒNG QUAN TRỌNG NHẤT (Thêm dòng này vào đầu tiên):
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',

        # Các dòng mặc định khác (giữ nguyên hoặc thêm vào):
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}