# Generated by Django 5.2.7 on 2026-01-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelservice',
            name='image',
            field=models.ImageField(null=True, upload_to='services/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars/%Y/%m'),
        ),
    ]
