# Generated by Django 5.2.7 on 2026-01-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelservice',
            name='latitude',
            field=models.FloatField(default=10.7769),
        ),
        migrations.AddField(
            model_name='travelservice',
            name='longitude',
            field=models.FloatField(default=106.7009),
        ),
    ]
