# Generated by Django 5.2.7 on 2026-01-14 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_travelservice_latitude_travelservice_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelservice',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='travelservice',
            name='longitude',
        ),
        migrations.AddField(
            model_name='travelservice',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='travel.category'),
        ),
        migrations.AlterField(
            model_name='travelservice',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='travelservice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='travelservice',
            name='slots_available',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='travelservice',
            name='slots_total',
            field=models.IntegerField(default=10),
        ),
    ]
